### ISSUE TITLE
Laravel 11 is not supporting ???

### ISSUE THREAD

**Issue by aashishtimalsina** [kutia-digital-agency/larafirebase#74]
Laravel 11 is not supporting ???

**Comment by gentritabazi** [comment]
https://github.com/gg-innovative/larafirebase

**Comment by aashishtimalsina** [comment]
@gentritabazi i want to update my code from laravel 9 to 11 but this package is not working ..

**Comment by gentritabazi** [comment]
You need to replace package to https://github.com/gg-innovative/larafirebase

`composer require gg-innovative/larafirebase`.
