### ISSUE TITLE
send notification to multiple device issuess !!

### ISSUE THREAD

**Issue by mosabalrojpany** [kutia-digital-agency/larafirebase#77]
i try to send notification to multiple mobile device but the function not working can any one help me bleaz for laravel 10

i want a function can i use it on my project

**Comment by midomario** [comment]
Hi, the package supports sending to array of tokens but sometimes if the array is huge FIREBASE may not send the notifications properly or at all, I resolved this partially by  creating a job and that will take a chunk of tokens and execute after n+3 minutes

**Comment by gentritabazi** [comment]
Please check the description of release 1.3.8, thanks!

https://github.com/kutia-software-company/larafirebase/releases/tag/1.3.8
