### ISSUE TITLE
Support laravel 11

### ISSUE THREAD

**Issue by rafi-al-ahmad** [kutia-digital-agency/larafirebase#78]
the package doesn't support laravel 11, is will there be a stable release to fix that?

**Comment by RichieMcMullen** [comment]
Bump

**Comment by gentritabazi** [comment]
https://github.com/kutia-software-company/larafirebase/releases/tag/1.3.8

**Comment by nemoitis** [comment]
I don't think the change was added on 1.3.8

![image](https://github.com/user-attachments/assets/d5d71602-d530-4cfb-a159-4ce04b73e50e)
