### ISSUE TITLE
How to find AUTHENTICATION_KEY in new updated console?

### ISSUE THREAD

**Issue by tarun-rayzon** [kutia-digital-agency/larafirebase#79]
I have installed your package and am trying to implement but I don't know where to find AUTHENTICATION_KEY in Firebase console. because in the new update firebase does not provide AUTHENTICATION_KEY.

**Comment by MandeepSingh1** [comment]
I also face the same issue; Firebase has deprecated the authentication key. @tarun-rayzon You have to work with their new API key and am not sure this package provides it.

**Comment by gentritabazi** [comment]
Please read the description here:

https://github.com/kutia-software-company/larafirebase/releases/tag/1.3.8
