### ISSUE TITLE
suddenly it doesn't work, haven't used firebase's latest mechanism/API?

### ISSUE THREAD

**Issue by amdkholil** [kutia-digital-agency/larafirebase#80]
Since September 4, 2024 until now, there are no more notifications from Firebase, even though nothing has changed from coding, and I think there is already the latest API from Firebase, have you used the last API?

**Comment by ferasalhallaknamaa3** [comment]
+1

**Comment by gentritabazi** [comment]
https://github.com/gg-innovative/larafirebase

**Comment by amdkholil** [comment]
> https://github.com/gg-innovative/larafirebase

thank you, this works great
