### ISSUE TITLE
Forgot to push tag for Laravel 11 support

### ISSUE THREAD

**Issue by TimeZHero** [kutia-digital-agency/larafirebase#83]
Hello, I noticed that there isn't any tag for the [Laravel 11 support](https://github.com/kutia-software-company/larafirebase/commit/947c3b74e363c39af7e26440ff2fdaffb15f8a02). 

Temporary fix would be to run:
`composer require kutia-software-company/larafirebase:dev-master#947c3b74e363c39af7e26440ff2fdaffb15f8a02`

**Comment by btnworks** [comment]
Now firebase server key is deprecated, will this module support for fcm api v1 auth2.0?

**Comment by gentritabazi** [comment]
Please check the description of release 1.3.8, thanks!

https://github.com/kutia-software-company/larafirebase/releases/tag/1.3.8
