### ISSUE TITLE
Deprecated FCM legacy APIs for HTTP and XMPP

### ISSUE THREAD

**Issue by akhelij** [kutia-digital-agency/larafirebase#84]
Apps using the deprecated FCM legacy APIs for HTTP and XMPP should migrate to the HTTP v1 API at the earliest opportunity. Sending messages (including upstream messages) with those APIs was deprecated on June 20, 2023, and [shutdown begins on July 22, 2024](https://firebase.google.com/support/faq#deprecated-api-shutdown)...
Here is the full article
https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by gentritabazi** [comment]
Please check the description of release 1.3.8, thanks!

https://github.com/kutia-software-company/larafirebase/releases/tag/1.3.8
